Install Pandas

pip install pandas

Import Pandas

In [ ]:
import pandas as pd

Read the data

File Handling

```
try:
  data = pd.read_csv('path_of_file')
except FileNotFoundError as e:
  print("File not found:", e)
```

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ChaiCode Full Stack Data Science Cohort/Phase 0 - Python Programming for Data Science/Pandas_18May_11AM/dataset.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Display the top 5 records in the data

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
data.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
10,902,0,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S

Display the last few records in the dataframe

In [ ]:
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
data.tail(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
403,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
406,1298,0,2,"Ware, Mr. William Jeffery",male,23.0,1,0,28666,10.5000,NaN,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
408,1300,1,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
410,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Data Structure: Dataframe

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
type(data['PassengerId'])

pandas.core.series.Series

Series in Depth: It's a one dimensional array-like structure in Pandas that can hold a sequence of value of any data type. Each value in a Series is linked with a associated label, known as the index. You can also customize the index labels in the series.

Create a series from scalar value with the custom index

In [ ]:
series_scalar = pd.Series(10, index=['a', 'b', 'c', 'd', 'e', 'f'])
print(series_scalar)

a    10
b    10
c    10
d    10
e    10
f    10
dtype: int64

In [ ]:
series_scalar['e']

np.int64(10)

In [ ]:
data = [10, 20, 30, 40, 50, 60, 70]
series_list = pd.Series(data)
print(series_list)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [ ]:
import numpy as np
data_array = np.array([10, 20, 30, 40, 50, 60])
series_custom_array = pd.Series(data_array, index=['a', 'b', 'c', 'd', 'e', 'f'])
series_custom_array

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [ ]:
data_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series_dict = pd.Series(data_dict)
series_dict

a    10
b    20
c    30
d    40
e    50
dtype: int64

Slicing

In [ ]:
series_dict[1:4]

b    20
c    30
d    40
dtype: int64

In [ ]:
series_dict['b':'d']

b    20
c    30
d    40
dtype: int64

Attributes in Series Data Structure

In [ ]:
data = ['New Delhi', 'Washington', 'London', 'Paris']
index = ['India', 'USA', 'UK', 'France']

series_capital_country = pd.Series(data, index=index)
print(series_capital_country)

India      New Delhi
USA       Washington
UK            London
France         Paris
dtype: object

In [ ]:
print("Index of the series_capital_country")
print(series_capital_country.index)

Index of the series_capital_country
Index(['India', 'USA', 'UK', 'France'], dtype='object')

In [ ]:
print(type(series_capital_country.index))

<class 'pandas.core.indexes.base.Index'>

In [ ]:
print("Values of the series_capital_country")
print(series_capital_country.values)

Values of the series_capital_country
['New Delhi' 'Washington' 'London' 'Paris']

Dtype is data type of each element in that type of data structure

In [ ]:
print("Data type of the series_capital_country")
print(series_capital_country.dtype)

Data type of the series_capital_country
object

In [ ]:
print("Shape of the series_capital_country")
print(series_capital_country.shape)

Shape of the series_capital_country
(4,)

In [ ]:
print("Size of the series_capital_country")
print(series_capital_country.size)

Size of the series_capital_country
4

In [ ]:
print("Is series_capital_country empty?")
print(series_capital_country.empty)

Is series_capital_country empty?
False

In [ ]:
print("Is series_capital_country contains NaN?")
print(series_capital_country.hasnans)

Is series_capital_country contains NaN?
False

In [ ]:
print("Is series_capital_country contains unique elements?")
print(series_capital_country.is_unique)

Is series_capital_country contains unique elements?
True

In [ ]:
print("Dimensions of the series_capital_country")
print(series_capital_country.ndim)

Dimensions of the series_capital_country
1

In [ ]:
empty_series = pd.Series()
print(empty_series)

Series([], dtype: object)

In [ ]:
print("Is empty_series empty?")
print(empty_series.empty)

Is empty_series empty?
True

Methods in Series Data Structure

In [ ]:
series_capital_country.head(2)

India     New Delhi
USA      Washington
dtype: object

In [ ]:
series_capital_country.tail(2)

UK        London
France     Paris
dtype: object

In [ ]:
marks = [85, 60, 74, 66, 89, 91]
students = ['Ram', 'Priya', 'Rashmi', 'Vidushi', 'Mohit', 'Karan']

series_students = pd.Series(marks, index=students)
print(series_students)

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
Karan      91
dtype: int64

To get the descriptive statistics of the given data

In [ ]:
series_students.describe()

count     6.000000
mean     77.500000
std      12.817956
min      60.000000
25%      68.000000
50%      79.500000
75%      88.000000
max      91.000000
dtype: float64

value_counts()

In [ ]:
series_students.value_counts()

85    1
60    1
74    1
66    1
89    1
91    1
Name: count, dtype: int64

sort_values()

In [ ]:
series_students.sort_values()

Priya      60
Vidushi    66
Rashmi     74
Ram        85
Mohit      89
Karan      91
dtype: int64

drop()



```
series_students = series_students.drop('Karan')
series_students
```

In [ ]:
series_students.drop('Karan', inplace=True)

In [ ]:
series_students

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
dtype: int64

isnull() -> Detect the missing values

In [ ]:
print(series_students.isnull())

Ram        False
Priya      False
Rashmi     False
Vidushi    False
Mohit      False
dtype: bool

In [ ]:
print(series_students.isnull().sum())

0

Task: Mathematical Operations on Series

1. Addition of two Series

2. Subtraction of two Series

3. Multiplication of two Series

4. Division of two Series

In [ ]:
series_students['Karan'] = 91
series_students

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
Karan      91
dtype: int64

Task: Simulate the same approach for a dataframe and you need to cover all the attributes and methods for the dataframe